// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://swqdwblafopmaikozpkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3cWR3YmxhZm9wbWFpa296cGtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyNzg1NzgsImV4cCI6MjA3NDg1NDU3OH0.rNcNtW7aPUnFCa40I4b8uScnKAUyaLT2awwlxtUDDWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);